export {
  FileIcon,
  FolderIcon,
  TrashIcon,
  SignupIcon,
  PricingIcon,
  DemoIcon,
  DocsIcon,
  EmailIcon,
  QuestionIcon,
  ChartIcon,
  ChangelogIcon,
  HandbookIcon,
  StoreIcon,
  WorkIcon,
  SwitchModeIcon,
  ProductOSIcon,
  GitHubIcon,
  PostHogLogo,
} from './FileIcon';