export {
  FileIcon,
  FolderIcon,
  TrashIcon,
  PricingIcon,
  DemoIcon,
  DocsIcon,
  EmailIcon,
  QuestionIcon,
  ChartIcon,
  ChangelogIcon,
  BilibiliIcon,
  ThisPCIcon,
  HandbookIcon,
  StoreIcon,
  WorkIcon,
  SwitchModeIcon,
  ProductOSIcon,
  GitHubIcon,
  TopazLogo,
  ArticleIcon,
  DriveIcon,
  OpticalDriveIcon,
  UserFolderIcon,
  AboutIcon,
  EssayIcon,
  FriendLinkIcon,
} from './FileIcon';